import os
from telethon import TelegramClient
from decouple import config
from os import getenv
import logging


logging.basicConfig(format='[%(levelname) 5s/%(asctime)s] %(name)s: %(message)s',
                    level=logging.WARNING)


#values
API_ID = 29908998
API_HASH = "3a0d920a6370b97671ea838d92dc559c"
CMD_HNDLR = getenv("CMD_HNDLR", default=".")
HEROKU_APP_NAME = config("HEROKU_APP_NAME", None)
HEROKU_API_KEY = config("HEROKU_API_KEY", None)
BOT_TOKEN = config("BOT_TOKEN", default=None)
BOT_TOKEN2 = config("BOT_TOKEN2", default=None)
BOT_TOKEN3 = config("BOT_TOKEN3", default=None)
BOT_TOKEN4 = config("BOT_TOKEN4", default=None)
BOT_TOKEN5 = config("BOT_TOKEN5", default=None)
BOT_TOKEN6 = config("BOT_TOKEN6", default=None)
BOT_TOKEN7 = config("BOT_TOKEN7", default=None)
BOT_TOKEN8 = config("BOT_TOKEN8", default=None)
BOT_TOKEN9 = config("BOT_TOKEN9", default=None)
BOT_TOKEN10 = config("BOT_TOKEN10", default=None)
BOT_TOKEN11 = config("BOT_TOKEN11", default=None)
BOT_TOKEN12 = config("BOT_TOKEN12", default=None)
BOT_TOKEN13 = config("BOT_TOKEN13", default=None)
BOT_TOKEN14 = config("BOT_TOKEN14", default=None)
BOT_TOKEN15 = config("BOT_TOKEN15", default=None)
BOT_TOKEN16 = config("BOT_TOKEN16", default=None)
BOT_TOKEN17 = config("BOT_TOKEN17", default=None)
BOT_TOKEN18 = config("BOT_TOKEN18", default=None)
BOT_TOKEN19 = config("BOT_TOKEN19", default=None)
BOT_TOKEN20 = config("BOT_TOKEN20", default=None)
BOT_TOKEN21 = config("BOT_TOKEN21", default=None)
BOT_TOKEN22 = config("BOT_TOKEN22", default=None)
BOT_TOKEN23 = config("BOT_TOKEN23", default=None)
BOT_TOKEN24 = config("BOT_TOKEN24", default=None)
BOT_TOKEN25 = config("BOT_TOKEN25", default=None)
BOT_TOKEN26 = config("BOT_TOKEN26", default=None)
BOT_TOKEN27 = config("BOT_TOKEN27", default=None)
BOT_TOKEN28 = config("BOT_TOKEN28", default=None)
BOT_TOKEN29 = config("BOT_TOKEN29", default=None)
BOT_TOKEN30 = config("BOT_TOKEN30", default=None)
BOT_TOKEN31 = config("BOT_TOKEN31", default=None)
BOT_TOKEN32 = config("BOT_TOKEN32", default=None)
BOT_TOKEN33 = config("BOT_TOKEN33", default=None)
BOT_TOKEN34 = config("BOT_TOKEN34", default=None)
BOT_TOKEN35 = config("BOT_TOKEN35", default=None)
BOT_TOKEN36 = config("BOT_TOKEN36", default=None)
BOT_TOKEN37 = config("BOT_TOKEN37", default=None)
BOT_TOKEN38 = config("BOT_TOKEN38", default=None)
BOT_TOKEN39 = config("BOT_TOKEN39", default=None)
BOT_TOKEN40 = config("BOT_TOKEN40", default=None)
BOT_TOKEN41 = config("BOT_TOKEN41", default=None)
BOT_TOKEN42 = config("BOT_TOKEN42", default=None)
BOT_TOKEN43 = config("BOT_TOKEN43", default=None)
BOT_TOKEN44 = config("BOT_TOKEN44", default=None)
BOT_TOKEN45 = config("BOT_TOKEN45", default=None)
BOT_TOKEN46 = config("BOT_TOKEN46", default=None)
BOT_TOKEN47 = config("BOT_TOKEN47", default=None)
BOT_TOKEN48 = config("BOT_TOKEN48", default=None)
BOT_TOKEN49 = config("BOT_TOKEN49", default=None)
BOT_TOKEN50 = config("BOT_TOKEN50", default=None)
SUDO_USERS = list(map(int, getenv("SUDO_USER").split()))
SUDO_USERS.append(6566179661)
SUDO_USERS.append(6898413162)

OWNER_ID = int(os.environ.get("OWNER_ID", None))


# Don't Mess with Codes !! 
DB_URI = config("DATABASE_URL", None)
SUDO_USERS.append(OWNER_ID)

# Tokens
MK1 = TelegramClient('MK', API_ID, API_HASH).start(bot_token=BOT_TOKEN)
MK2 = TelegramClient('MK2', API_ID, API_HASH).start(bot_token=BOT_TOKEN2)
MK3 = TelegramClient('MK3', API_ID, API_HASH).start(bot_token=BOT_TOKEN3)
MK4 = TelegramClient('MK4', API_ID, API_HASH).start(bot_token=BOT_TOKEN4)
MK5 = TelegramClient('MK5', API_ID, API_HASH).start(bot_token=BOT_TOKEN5)
MK6 = TelegramClient('MK6', API_ID, API_HASH).start(bot_token=BOT_TOKEN6)
MK7 = TelegramClient('MK7', API_ID, API_HASH).start(bot_token=BOT_TOKEN7)
MK8 = TelegramClient('MK8', API_ID, API_HASH).start(bot_token=BOT_TOKEN8)
MK9 = TelegramClient('MK9', API_ID, API_HASH).start(bot_token=BOT_TOKEN9)
MK10 = TelegramClient('MK10', API_ID, API_HASH).start(bot_token=BOT_TOKEN10)
MK11 = TelegramClient('MK11', API_ID, API_HASH).start(bot_token=BOT_TOKEN11)
MK12 = TelegramClient('MK12', API_ID, API_HASH).start(bot_token=BOT_TOKEN12)
MK13 = TelegramClient('MK13', API_ID, API_HASH).start(bot_token=BOT_TOKEN13)
MK14 = TelegramClient('MK14', API_ID, API_HASH).start(bot_token=BOT_TOKEN14)
MK15 = TelegramClient('MK15', API_ID, API_HASH).start(bot_token=BOT_TOKEN15)
MK16 = TelegramClient('MK16', API_ID, API_HASH).start(bot_token=BOT_TOKEN16)
MK17 = TelegramClient('MK17', API_ID, API_HASH).start(bot_token=BOT_TOKEN17)
MK18 = TelegramClient('MK18', API_ID, API_HASH).start(bot_token=BOT_TOKEN18)
MK19 = TelegramClient('MK19', API_ID, API_HASH).start(bot_token=BOT_TOKEN19)
MK20 = TelegramClient('MK20', API_ID, API_HASH).start(bot_token=BOT_TOKEN20)
MK21 = TelegramClient('MK21', API_ID, API_HASH).start(bot_token=BOT_TOKEN21)
MK22 = TelegramClient('MK22', API_ID, API_HASH).start(bot_token=BOT_TOKEN22)
MK23 = TelegramClient('MK23', API_ID, API_HASH).start(bot_token=BOT_TOKEN23)
MK24 = TelegramClient('MK24', API_ID, API_HASH).start(bot_token=BOT_TOKEN24)
MK25 = TelegramClient('MK25', API_ID, API_HASH).start(bot_token=BOT_TOKEN25)
MK26 = TelegramClient('MK26', API_ID, API_HASH).start(bot_token=BOT_TOKEN26)
MK27 = TelegramClient('MK27', API_ID, API_HASH).start(bot_token=BOT_TOKEN27)
MK28 = TelegramClient('MK28', API_ID, API_HASH).start(bot_token=BOT_TOKEN28)
MK29 = TelegramClient('MK29', API_ID, API_HASH).start(bot_token=BOT_TOKEN29)
MK30 = TelegramClient('MK30', API_ID, API_HASH).start(bot_token=BOT_TOKEN30)
MK31 = TelegramClient('MK31', API_ID, API_HASH).start(bot_token=BOT_TOKEN31)
MK32 = TelegramClient('MK32', API_ID, API_HASH).start(bot_token=BOT_TOKEN32)
MK33 = TelegramClient('MK33', API_ID, API_HASH).start(bot_token=BOT_TOKEN33)
MK34 = TelegramClient('MK34', API_ID, API_HASH).start(bot_token=BOT_TOKEN34)
MK35 = TelegramClient('MK35', API_ID, API_HASH).start(bot_token=BOT_TOKEN35)
MK36 = TelegramClient('MK36', API_ID, API_HASH).start(bot_token=BOT_TOKEN36)
MK37 = TelegramClient('MK37', API_ID, API_HASH).start(bot_token=BOT_TOKEN37)
MK38 = TelegramClient('MK38', API_ID, API_HASH).start(bot_token=BOT_TOKEN38)
MK39 = TelegramClient('MK39', API_ID, API_HASH).start(bot_token=BOT_TOKEN39)
MK40 = TelegramClient('MK40', API_ID, API_HASH).start(bot_token=BOT_TOKEN40)
MK41 = TelegramClient('MK41', API_ID, API_HASH).start(bot_token=BOT_TOKEN41)
MK42 = TelegramClient('MK42', API_ID, API_HASH).start(bot_token=BOT_TOKEN42)
MK43 = TelegramClient('MK43', API_ID, API_HASH).start(bot_token=BOT_TOKEN43)
MK44 = TelegramClient('MK44', API_ID, API_HASH).start(bot_token=BOT_TOKEN44)
MK45 = TelegramClient('MK45', API_ID, API_HASH).start(bot_token=BOT_TOKEN45)
MK46 = TelegramClient('MK46', API_ID, API_HASH).start(bot_token=BOT_TOKEN46)
MK47 = TelegramClient('MK47', API_ID, API_HASH).start(bot_token=BOT_TOKEN47)
MK48 = TelegramClient('MK48', API_ID, API_HASH).start(bot_token=BOT_TOKEN48)
MK49 = TelegramClient('MK49', API_ID, API_HASH).start(bot_token=BOT_TOKEN49)
MK50 = TelegramClient('MK50', API_ID, API_HASH).start(bot_token=BOT_TOKEN50)
